name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Rustup
      run: rustup target add i686-pc-windows-msvc
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: vciproxy.exe
        path: target/i686-pc-windows-msvc/debug/vciproxy.exe
